### ISSUE TITLE
the ShuffleNet structure is not consistent with the structure listed in the paper

### ISSUE THREAD

**Issue by Chen-Chang** [megvii-model/ShuffleNet-Series#39] opened 2020-08-04 02:31 UTC
In the original paper, the first pointwise group conv is followed by channel shuffle operarion. But in the ShufflenetV1block, it is followed by a DWConv.

**Comment by nmaac** [comment] 2020-08-04 03:49
Duplicate of #16

**Closed** 2020-08-04 05:00 UTC
Labels: duplicate
